apiVersion: v1
kind: Pod
metadata:
  labels:
    app: keycloak-postgres
  name: keycloak-postgres
spec:
  containers:
  - env:
    - name: POSTGRES_USER
      value: admin
    - name: POSTGRES_PASSWORD
      value: admin
    - name: POSTGRES_DB
      value: keycloakdb
    image: keycloak-postgres:17.0
    name: keycloak-postgres
    ports:
    - containerPort: 5432
