apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.62.0
          ports:
            - containerPort: 4317  # OTLP gRPC
            - containerPort: 5775  # Thrift UDP
            - containerPort: 6831  # Thrift UDP
            - containerPort: 6832  # Thrift UDP
            - containerPort: 5778  # HTTP for health checks
            - containerPort: 14250  # gRPC
            - containerPort: 14268  # HTTP for spans
            - containerPort: 16686  # HTTP for the UI
          env:
            - name: COLLECTOR_ZIPKIN_HTTP_PORT
              value: "9411"
            - name: QUERY_BASE_PATH
              value: "/jaeger"  # The base URL
          args:
            - "--reporter.type=grpc"
            - "--reporter.grpc.host-port=jaeger-collector:14250"
            - "--query.base-path=/jaeger"
