apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  type: ClusterIP
  ports:
    - name: thrift-udp
      port: 5775
      targetPort: 5775
    - name: thrift-udp-6831
      port: 6831
      targetPort: 6831
    - name: thrift-udp-6832
      port: 6832
      targetPort: 6832
    - name: http-health
      port: 5778
      targetPort: 5778
    - name: grpc
      port: 14250
      targetPort: 14250
    - name: http-spans
      port: 14268
      targetPort: 14268
    - name: http-ui
      port: 16686
      targetPort: 16686
    - name: otlp
      port: 4317
      targetPort: 4317
  selector:
    app: jaeger
