# metrics-server-clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-server
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/metrics", "pods", "pods/metrics", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
