apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  labels:
    app: fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-app
        image: fastapi-app:latest
        ports:
        - containerPort: 8010  # Use port 8010 inside the container
        env:
        - name: MONGODB_URL
          value: "mongodb://dev:MongoDBDev@localhost:27017/dev?directConnection=true&authSource=dev"
        - name: DATABASE_NAME
          value: "dev"
        - name: COLLECTION_NAME
          value: "sample"
        - name: ALLOWED_ORIGINS
          value: "*"
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 8010  # Expose port 8010 on the service
      targetPort: 8010  # Map to container port 8010
  type: LoadBalancer

