version: '3.8'

services:
  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8010:8010"  # Map container port 8010 to host port 8010
    environment:
      MONGODB_URL: mongodb://dev:MongoDBDev@localhost:27017/dev?directConnection=true&authSource=dev
      DATABASE_NAME: dev
      COLLECTION_NAME: sample
      ALLOWED_ORIGINS: "*"

