apiVersion: v1
kind: Pod
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  containers:
  - env:
    - name: POSTGRES_USER
      value: admin
    - name: POSTGRES_PASSWORD
      value: admin
    - name: POSTGRES_DB
      value: keycloakdb
    image: postgres:17.0
    name: postgres
    ports:
    - containerPort: 5432
